 // Hàm hiển thị profile học sinh
      function apShowProfile(studentId) {
        // Ẩn danh sách học sinh
        document.querySelector(".ap-student-list-view").style.display = "none";

        // Hiển thị profile
        const profileView = document.querySelector(".ap-profile-view");
        profileView.style.display = "flex";

        // Cuộn lên đầu phần profile
        profileView.scrollIntoView({ behavior: "smooth", block: "start" });

        // Lấy dữ liệu học sinh (có thể thay bằng API call)
        const studentData = apGetStudentData(studentId);

        // Điền dữ liệu vào profile
        if (studentData) {
          document.querySelector(".ap-profile-name").textContent =
            studentData.name;
          document.querySelector(".ap-profile-id").textContent = studentData.id;
          document.querySelector(".ap-profile-class").textContent =
            studentData.class;
          document.querySelector(".ap-profile-dob").textContent =
            studentData.dob;
          document.querySelector(".ap-profile-hometown").textContent =
            studentData.hometown;
          document.querySelector(".ap-profile-gpa").textContent =
            studentData.gpa;
          document.querySelector(".ap-profile-fav-subject").textContent =
            studentData.favSubject;
          document.querySelector(".ap-profile-food").textContent =
            studentData.food;
          document.querySelector(".ap-profile-excellent").textContent =
            studentData.excellent;
          document.querySelector(".ap-profile-avatar").src = studentData.avatar;
        }
      }

      // Hàm quay lại danh sách
      function apBackToList() {
        document.querySelector(".ap-student-list-view").style.display = "flex";
        document.querySelector(".ap-profile-view").style.display = "none";

        // Cuộn lên đầu danh sách
        document
          .querySelector(".ap-student-list-view")
          .scrollIntoView({ behavior: "smooth" });
      }

      // Hàm giả lập dữ liệu học sinh
      function apGetStudentData(studentId) {
        const students = {
          1: {
            name: "Đào Châu Anh",
            id: "D4-K69-VĐ-001",
            class: "D4",
            dob: "25/05/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal.png",
          },
          2: {
            name: "Đỗ Phương Quỳnh Anh",
            id: "D4-K69-VĐ-002",
            class: "D4",
            dob: "04/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (1).png",
          },
          3: {
            name: "Đặng Trâm Anh",
            id: "D4-K69-VĐ-003",
            class: "D4",
            dob: "23/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (2).png",
          },
          4: {
            name: "Lưu Quỳnh Anh",
            id: "D4-K69-VĐ-004",
            class: "D4",
            dob: "30/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (3).png",
          },
          5: {
            name: "Nguyễn Hiền Anh",
            id: "D4-K69-VĐ-005",
            class: "D4",
            dob: "24/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (4).png",
          },
          6: {
            name: "Nguyễn Phúc Anh",
            id: "D4-K69-VĐ-006",
            class: "D4",
            dob: "04/04/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (5).png",
          },
          7: {
            name: "Nguyễn Trâm Anh",
            id: "D4-K69-VĐ-007",
            class: "D4",
            dob: "20/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (6).png",
          },
          8: {
            name: "Phạm Thu Anh",
            id: "D4-K69-VĐ-008",
            class: "D4",
            dob: "11/12/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (7).png",
          },
          9: {
            name: "Trịnh Tài Anh",
            id: "D4-K69-VĐ-009",
            class: "D4",
            dob: "14/07/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (14).png",
          },
          10: {
            name: "Vũ Linh Anh",
            id: "D4-K69-VĐ-010",
            class: "D4",
            dob: "16/10/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (8).png",
          },
          11: {
            name: "Hà Minh Châu",
            id: "D4-K69-VĐ-011",
            class: "D4",
            dob: "18/10/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (9).png",
          },
          12: {
            name: "Nguyễn Vũ Hà Châu",
            id: "D4-K69-VĐ-012",
            class: "D4",
            dob: "28/08/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (11).png",
          },
          13: {
            name: "Hoàng Khánh Chi",
            id: "D4-K69-VĐ-013",
            class: "D4",
            dob: "23/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (12).png",
          },
          14: {
            name: "Phạm Linh Chi",
            id: "D4-K69-VĐ-014",
            class: "D4",
            dob: "21/05/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (10).png",
          },
          15: {
            name: "Lê Gia Hân",
            id: "D4-K69-VĐ-015",
            class: "D4",
            dob: "29/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (16).png",
          },
          16: {
            name: "Hoàng Minh Hiếu",
            id: "D4-K69-VĐ-016",
            class: "D4",
            dob: "15/12/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (13).png",
          },
          17: {
            name: "Trịnh Phúc Hưng",
            id: "D4-K69-VĐ-017",
            class: "D4",
            dob: "09/10/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (15).png",
          },
          18: {
            name: "Nguyễn Anh Khoa",
            id: "D4-K69-VĐ-018",
            class: "D4",
            dob: "25/08/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (18).png",
          },
          19: {
            name: "Nguyễn Công Khôi",
            id: "D4-K69-VĐ-019",
            class: "D4",
            dob: "30/12/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (17).png",
          },
          20: {
            name: "Nguyễn Minh Khôi",
            id: "D4-K69-VĐ-020",
            class: "D4",
            dob: "27/08/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animal (19).png",
          },
          21: {
            name: "Trần Mai Khuê",
            id: "D4-K69-VĐ-021",
            class: "D4",
            dob: "02/07/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/animalala.png",
          },
          22: {
            name: "Phan Trúc Lam",
            id: "D4-K69-VĐ-022",
            class: "D4",
            dob: "21/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/artist.png",
          },
          23: {
            name: "Lê Ngọc Linh",
            id: "D4-K69-VĐ-023",
            class: "D4",
            dob: "10/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/businessman.png",
          },
          24: {
            name: "Nguyễn Khánh Linh",
            id: "D4-K69-VĐ-024",
            class: "D4",
            dob: "11/06/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/courier.png",
          },
          25: {
            name: "Trương Ngọc Khánh Linh",
            id: "D4-K69-VĐ-025",
            class: "D4",
            dob: "21/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/courier (1).png",
          },
          26: {
            name: "Trịnh Thủy Linh",
            id: "D4-K69-VĐ-026",
            class: "D4",
            dob: "12/02/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/courier (2).png",
          },
          27: {
            name: "Vũ Khánh Linh",
            id: "D4-K69-VĐ-027",
            class: "D4",
            dob: "28/06/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/chef.png",
          },
          28: {
            name: "Ngô Ngọc Mai",
            id: "D4-K69-VĐ-028",
            class: "D4",
            dob: "21/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/judge.png",
          },
          29: {
            name: "Phạm Quý Mạnh",
            id: "D4-K69-VĐ-029",
            class: "D4",
            dob: "17/03/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/chemist.png",
          },
          30: {
            name: "Phạm Hà My",
            id: "D4-K69-VĐ-030",
            class: "D4",
            dob: "21/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/diver.png",
          },
          31: {
            name: "Đỗ Ngọc Khánh Nam",
            id: "D4-K69-VĐ-031",
            class: "D4",
            dob: "05/02/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/driver.png",
          },
          32: {
            name: "Cao Bảo Ngọc",
            id: "D4-K69-VĐ-032",
            class: "D4",
            dob: "29/08/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/doctor.png",
          },
          33: {
            name: "Nguyễn Hồng Ngọc",
            id: "D4-K69-VĐ-033",
            class: "D4",
            dob: "24/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/farmer.png",
          },
          34: {
            name: "Trần Thảo Nguyên",
            id: "D4-K69-VĐ-034",
            class: "D4",
            dob: "21/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/firefighter.png",
          },
          35: {
            name: "Nguyễn Tuấn Phong",
            id: "D4-K69-VĐ-035",
            class: "D4",
            dob: "20/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/graphic-designer.png",
          },
          36: {
            name: "Đào Minh Phúc",
            id: "D4-K69-VĐ-036",
            class: "D4",
            dob: "13/11/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/lifeguard.png",
          },
          37: {
            name: "Nguyễn Chí Quân",
            id: "D4-K69-VĐ-037",
            class: "D4",
            dob: "25/08/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/mechanic.png",
          },
          38: {
            name: "Vũ Thu Thủy",
            id: "D4-K69-VĐ-038",
            class: "D4",
            dob: "08/04/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/korean-movie.png",
          },
          39: {
            name: "Chử Anh Thư",
            id: "D4-K69-VĐ-039",
            class: "D4",
            dob: "12/04/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/painter.png",
          },
          40: {
            name: "Nguyễn Thị Anh Thư",
            id: "D4-K69-VĐ-040",
            class: "D4",
            dob: "07/04/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/pilot.png",
          },
          41: {
            name: "Nguyễn Thị Minh Thư",
            id: "D4-K69-VĐ-041",
            class: "D4",
            dob: "05/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/shopper.png",
          },
          42: {
            name: "Lê Hà Trang",
            id: "D4-K69-VĐ-042",
            class: "D4",
            dob: "25/04/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/shopper (1).png",
          },
          43: {
            name: "Ngô Bảo Trân",
            id: "D4-K69-VĐ-043",
            class: "D4",
            dob: "10/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/postman.png",
          },
          44: {
            name: "Trịnh Thanh Trức",
            id: "D4-K69-VĐ-044",
            class: "D4",
            dob: "28/05/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/shopper (2).png",
          },
          45: {
            name: "Nguyễn Quang Tuấn",
            id: "D4-K69-VĐ-045",
            class: "D4",
            dob: "10/12/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/romawi.png",
          },
          46: {
            name: "Đỗ Minh Tùng",
            id: "D4-K69-VĐ-035",
            class: "D4",
            dob: "09/09/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/police.png",
          },
          47: {
            name: "Nguyễn Thu Uyên",
            id: "D4-K69-VĐ-047",
            class: "D4",
            dob: "05/01/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/teacher.png",
          },
          48: {
            name: "Đoàn Tường Vy",
            id: "D4-K69-VĐ-048",
            class: "D4",
            dob: "06/11/2009",
            hometown: "Hà Nội",
            gpa: "10",
            favSubject: "",
            food: "",
            excellent: "Xuất sắc",
            avatar: "img/cute/traveller.png",
          },
        };

        return students[studentId];
      }

      // Khởi tạo khi trang tải xong
      document.addEventListener("DOMContentLoaded", function () {
        // Thêm sự kiện click cho các thẻ học sinh
        document.querySelectorAll(".ap-student-card").forEach((card) => {
          card.addEventListener("click", function () {
            const studentId = this.getAttribute("data-student-id");
            apShowProfile(studentId);
          });
        });
      });
